name: network_reachability
description: A starting point for Dart libraries or applications.
publish_to: "pub.dev"
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter_rust_bridge: 2.11.1
  rust_lib_network_reachability:
    path: rust_builder


dev_dependencies:
  build_runner: ^2.11.0
  integration_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.25.6
