[package]
name = "rust_lib_network_reachability"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"

tokio = { version = "1.49.0", features = ["full"] }
anyhow = "1.0.101"
futures = "0.3.31"
socket2 = "0.6.2"
ipnet = "2.11.0"
trust-dns-resolver = "0.23.2"
reqwest = "0.13.2"

network-interface = "2.0.5"
chrono = "0.4"
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
